# Site settings
title: APLY - Advanced PLatform to FLY
email: contactus@aply.biz
description: > # this means to ignore newlines until "baseurl:"
    The Jupyter Notebook is a web-based interactive computing platform. The
    notebook combines live code, equations, narrative text, visualizations,
    interactive dashboards and other media.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://aply.biz" # the base hostname & protocol for your site
github_username:  gunman97 

# Build settings
markdown: kramdown
highlighter: rouge

exclude: [vendor]
include: [".well-known"]

plugins:
  - jekyll-redirect-from
